### ISSUE TITLE
please add github workerflow

### ISSUE THREAD

**Issue by weironz** [zhaohuabing/zhaohuabing.github.io#2]
create a new branch use workerflow for auto `hugo --minify` ，i can know what you have config in your config.toml

refer:https://github.com/willzhang/willzhang.github.io

create .github/workflows/hugo.yml

```
name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          publish_dir: ./public
```
